### ISSUE TITLE
请问界面中的脚本和API调用有相关使用说明吗？

### ISSUE THREAD

**Issue by zhueh** [dicarne/Mykey#3]
如题，谢谢

**Comment by dicarne** [comment]
关于API：
一个python示例，其中key就是按键
requests.post("http://127.0.0.1:15692/send", json={
        "key": "ctrl\\v"
    })

**Comment by dicarne** [comment]
脚本功能做的比较抽象……
在应用程序同级的`scripts`目录下创建txt文档将被视作脚本，其内容大致如下：
```
-x 46.730
LM
-> 49.599
f
-> 53.433
f\j
-> 57.000
j\f
-> 58.733
f
-> 1:00.466
j
-> 1:01.133
f
-> 1:02.233
00:01:46.399
f\j
00:01:47.233
f
00:01:48.199
f\j
00:01:49.033
f
00:01:49.966
f\j
00:01:50.799
f
00:01:51.766

```

其中，大致遵循着一行指令、一行按键的规则。指令行如`-x 46.730`，`-x`是指令，`40.730`代表40秒730毫秒。

指令介绍如下：
* `-x time` （下一行是按键）设置一个基准时间
* `-> time` （下一行是按键）在(time-基准时间)时执行。如果`-x 10.000`后有一个`-> 12.000`，那么将在脚本开始后的2秒执行`->`指令下一行的按键而不是12秒后。`->`可以省略，也就是只写一个时间也是这个效果。
* `-r` 表示从头开始，后面不跟着按键。

**Comment by zhueh** [comment]
谢谢~！
